collate/tools/colcmp: fix some breakage from cftypes cgo changes in Go 1.10
I used C.kCFAllocatorDefault (defined as NULL in C) instead of 0 so
it'd compile on older Go versions.

After this change, only one compilation error remains:

./darwin.go:48: cannot use l (type _Ctype_CFStringRef) as type *_Ctype_struct___CFString in argument to func literal

Updates golang/go#22900

Change-Id: I55dfbf560c18b4ebaedf4d96340423c0b1ae445a
Reviewed-on: https://go-review.googlesource.com/80215
Run-TryBot: Brad Fitzpatrick <bradfitz@golang.org>
TryBot-Result: Gobot Gobot <gobot@golang.org>
Reviewed-by: Marcel van Lohuizen <mpvl@golang.org>